### ISSUE TITLE
Email Text box not responsive

### ISSUE THREAD

**Issue by prabuddha369** [Kickstart-in-net/frontend#6]
![image](https://github.com/user-attachments/assets/84cf6f83-ebc5-4476-b03e-df20f35f2357)

The Email textbox beside Sign up for kickstart button is not responsive over different desktop screen widths.

**Comment by soumik-github-4223** [comment]
![image](https://github.com/user-attachments/assets/4da23bc4-26b7-4410-94bf-59c04d3d950f)
